import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Profile from '@/components/Profile'
import Navbar from '@/components/Navbar'
import Script from 'next/script'
import About from '@/components/About'
import Resume from '@/components/Resume'
import Projects from '@/components/Projects'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Anand Lunawat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className='light-mode fixed w-[100vw] h-[100vh]'>
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-L678VG62DJ"></Script>
      <Script id="google-analytics">
        {
          `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-L678VG62DJ');
          `
        }
      </Script>
      <body className={`${inter.className} fixed children w-[100vw] h-[100vh] lg:overflow-hidden`}>
        <div className='flex flex-col md:p-4 p-2 gap-4'>
          <Navbar />
          <div className='lg:flex max-md:h-full gap-4 lg:flex-row w-full'>
            <Profile />
            <div className="max-h-screen scroll-smooth w-full children pb-44 lg:max-h-[80vh] overflow-y-auto">
              {children}
              <div id='projects'><Projects /></div>
              <div id='about'><About /></div>
              <div id='resume'><Resume /></div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
